name: ucvm-dev-ci

on:
  push:
    branches: [ basin ]

jobs:
  ucvm-build-cvmh:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV
    - name: checkout ucvm basin
      uses: actions/checkout@v2
      with: 
        ref: basin
    - name: build ucvm with cvmh
      run: ./.github/scripts/ucvm-build.sh "cvmh"
      shell: bash
    - name: test ucvm with cvmh
      run: ./.github/scripts/ucvm-test.sh
      shell: bash

  ucvm-build-cvms-cvmh:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV
    - name: checkout ucvm basin
      uses: actions/checkout@v2
      with: 
        ref: basin
    - name: checkout ucvm toPython3
      uses: actions/checkout@v2
    - name: build ucvm with cvms and cvmh
      run: ./.github/scripts/ucvm-build.sh "cvms,cvmh"
      shell: bash
    - name: test ucvm with cvms and cvmh
      run: ./.github/scripts/ucvm-test.sh
      shell: bash

  ucvm-build-albacore-cvlsu-ivlsu-wfcvm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV

    - name: checkout ucvm basin
      uses: actions/checkout@v2
      with: 
        ref: basin

    - name: build ucvm with albacore, cvlsu, ivlsu and wfcvm
      run: ./.github/scripts/ucvm-build.sh "albacore,cvlsu,ivlsu,wfcvm"
      shell: bash
    - name: test ucvm with albacore, cvlsu, ivlsu and wfcvm
      run: ./.github/scripts/ucvm-test.sh
      shell: bash

  ucvm-build-cencal-cvms:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/target" >> $GITHUB_ENV

    - name: checkout ucvm basin
      uses: actions/checkout@v2
      with: 
        ref: basin

    - name: build ucvm with cencal cvms
      run: ./.github/scripts/ucvm-build.sh "cencal,cvms"
      shell: bash
    - name: test ucvm with cencal and cvms
      run: ./.github/scripts/ucvm-test.sh
      shell: bash
